package com.example.appweather3.models

data class Data(
    val sunrise: Double,
    val sunset: Double,
    val humidity: Int,
    val observation_time: String,
    val cloudcover: String,
    val windspeedKmph:Int,
    val pressure: Int,
    val weatherDesc:String,
    val visibility: Int,
    val weatherCode: Int,
    val time :Int,
    val tempC : Int,
    val FeelsLikeC:Int,
    val WindChillC:Int,
    val windspeedMiles:Int,
    val chanceoffog: Int,
    val chanceoffrost: Int,
    val chanceofhightemp: Int,
    val chanceofovercast: Int,
    val chanceofrain: Int,
    val chanceofremdry: Int,
    val chanceofsnow: Int,
    val chanceofsunshine: Int,
    val chanceofthunder: Int,
    val chanceofwindy: Int,
    val areaName : String,
    val country : String,
    val type: String,
    val query: String,
    val astronomy: List<Astronomy>,
    val date: String,
    val maxtempC: Int,
    val mintempC: Int,
)
